name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  opensuse-test:
    runs-on: ubuntu-latest  
    container:
      image: opensuse/leap
    steps:
      - name: prepare system
        run: |
          cat /etc/os-release
          zypper refresh
          zypper install -y git gcc make
          zypper install -y libXt6 libXt-devel libXm4 motif-devel libX11-6 libX11-devel
          
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: make
      run: pwd; echo "--.--"; ls; echo "--..--"; ls ..; echo "--Makefile--";cat Makefile; echo "----"; make all

